<div class="span8 offset2">
	<h1><?php echo $this->gravatar('morfreek.other@gmail.com'); ?> CxC Fernando</h1>

	<div class="well">
		<div id="mapa" style="height:300px;"></div>
	</div>
</div>

<script type="text/javascript">
var map;
$(function(){
	map = new GMaps({
	    div: '#mapa',
        lat: -36.806536,
        lng: -73.050156
	});

	GMaps.geolocate({
		success: function(position) {
	    	map.setCenter(position.coords.latitude, position.coords.longitude);
	    	map.addMarker({
				lat: position.coords.latitude,
				lng: position.coords.longitude
			});
		}
	});

    <?php $i=0; ?>
    <?php foreach($this->result as $aux){ ?>
	GMaps.geocode({
        address: <?php echo $aux[3].", ".$aux[1] ?>,
        callback: function(results, status){
            if(status=='OK'){
              	var latlng = results[0].geometry.location;
              	map.setCenter(latlng.lat(), latlng.lng());
              	map.addMarker({
                	lat: latlng.lat(),
                	lng: latlng.lng(),
                	click: function(e) {
						alert('Seleccionaste el punto');
					}
              	});
            }
        }
    });
    <?php ($i>10) ? break : ++$i; ?>
    <?php } ?>
});
</script>