<div class="bg-header">
	<div class="span6 offset3">

		<div class="logo">
			<img src="http://placehold.it/640x200" alt="Quiero una farmacia" />
		</div>

		<div class="ubicacion">
			<label>Tu dirección:</label>
			<input type="text" id="ubicacion" class="input-xlarge" value="Concepción, Chile" readonly />
		</div>

		<h1><?php echo $this->gravatar('fernando.toloza@gmail.com'); ?> CxC Fernando</h1>

		<div class="well">
			<div id="mapa" style="height:300px;"></div>
		</div>
	</div>
</div>

<script type="text/javascript">
var map;
$(function(){
	map = new GMaps({
	    div: '#mapa',
        lat: -36.806536,
        lng: -73.050156
	});

	// GMaps.geocode({
	// 	address: $('#address').val(),
	// 	callback: function(results, status) {
	// 		if (status == 'OK') {
	// 			var latlng = results[0].geometry.location;
	// 			map.setCenter(latlng.lat(), latlng.lng());
	// 			map.addMarker({
	// 				lat: latlng.lat(),
	// 				lng: latlng.lng()
	// 			});
	// 		}
	// 	}
	// });

	GMaps.geolocate({
		success: function(position) {
	    	map.setCenter(position.coords.latitude, position.coords.longitude);
	    	map.addMarker({
				lat: position.coords.latitude,
				lng: position.coords.longitude
			});
		}
		// error: function(error) {
	 	//    	alert('Geolocation failed: '+error.message);
		// },
		// not_supported: function() {
	 	//   		alert("Your browser does not support geolocation");
		// },
		//  	always: function() {
		//    	alert("Done!");
		//  	}
	});

	// map.addMarker({
	// 	lat: -12.043333,
	// 	lng: -77.028333,
	// 	title: 'Lima',
	// 	click: function(e) {
	// 		alert('You clicked in this marker');
	// 	}
	// });

	GMaps.geocode({
        address: "Diagonal Las Torres 2264, Santiago",
        callback: function(results, status){
            if(status=='OK'){
              	var latlng = results[0].geometry.location;
              	map.setCenter(latlng.lat(), latlng.lng());
              	map.addMarker({
                	lat: latlng.lat(),
                	lng: latlng.lng(),
                	click: function(e) {
						alert('Seleccionaste el punto');
					}
              	});
            }
        }
    });
});
</script>