<div class="login">
	<h1>Iniciar sesión</h1>

	<form id="form-login" action="/registro/index/log/" method="post">
 		<input type="text" class="span12" name="email" placeholder="Email" />
 		<input type="password" class="span12" name="pass" placeholder="Contraseña" />

 		<input type="submit" class="btn btn-large btn-medicamento" value="Iniciar sesión" />
	</form>
	<div class="info">Si no posee una cuenta debe <a href="/registro/">registrarse</a></div>
</div>
